# Generated by Django 3.2.16 on 2022-12-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_auto_20221218_1446"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="id_done",
            new_name="is_done",
        ),
    ]
