# Generated by Django 3.2.16 on 2022-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_postversion_post'),
        ('website', '0009_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Category'),
        ),
    ]
