# Generated by Django 3.2.16 on 2022-12-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_slider_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='order',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
