# Generated by Django 3.2.16 on 2022-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.png', height_field=900, null=True, upload_to='profiles/', width_field=900),
        ),
    ]
