# Generated by Django 3.2.16 on 2022-12-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_auto_20221211_1451"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image_height",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="image_width",
        ),
    ]
