# Generated by Django 3.2.16 on 2022-12-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20221216_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='First will be main category', to='blog.Category'),
        ),
    ]
