# Generated by Django 3.2.16 on 2022-12-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_auto_20221221_0747"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postversion",
            name="post",
            field=models.ForeignKey(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
    ]
