# Generated by Django 3.2.16 on 2022-12-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postversion_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postversion',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
