# Generated by Django 3.2.16 on 2022-12-22 06:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_alter_post_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2022, 12, 22, 6, 2, 38, 28897, tzinfo=utc),
                null=True,
            ),
        ),
    ]
